ignore:
  - "cmd/node/main.go"
  - "internal/eth/mocks"
  - "internal/network/mocks"
  - "scripts/db_local_compare"
  - "scripts/dump"
coverage:
  status:
    project:
      default:
        target: 75
