name: CI

on:
  push:
    branches: [ "main" ]  # or whatever branches you want to build on
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v3

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"  # or whichever version you need

      # 3. Install go-task
      - name: Install go-task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      # 4. Run tests via Task
      - name: Test
        run: |
          task test

      # 5. Build the app via Task
      - name: Build
        run: |
          task build