name: CI

on:
  push:
    branches: [ "main" ]  # or whatever branches you want to build on
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.4"

      - name: Install go-task
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          task build

      - name: Run tests and coverage
        run: |
          task coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          flags: unittests
          fail_ci_if_error: true